import images from "../../constants/images";
import { ICategory } from "./category.interface";

export const categoryLevel0:Array<ICategory> = [
    {   id: 1, 
        name:'Мясо', 
        iconName: images.meat,
    },
    {   id: 2, 
        name:'Молоко+', 
        iconName: images.milkCheese
    },
    {   id: 3, 
        name:'Птица+', 
        iconName: images.chicken
    },
    { 
        id: 4, 
        name:'Овощи', 
        iconName: images.vegetables
    },  
    {   id: 5, 
        name:'Фрукты', 
        iconName: images.fruits
    },
    {   id: 6, 
        name:'Ягоды', 
        iconName: images.berries
    },
    {   id: 7, 
        name:'Грибы', 
        iconName: images.mushroom
    },
    {   id: 8, 
        name:'Мед+', 
        iconName: images.honey
    },
    {   id: 9, 
        name:'Масла', 
        iconName: images.oil
    }
]; 

export const categoryLevel1: Array<ICategory> = [
    // мясо
    {   id: 1, 
        parentId: 1,
        name:'Говядина', 
        iconName:images.cow,
    },
    {   id: 2, 
        parentId: 1,
        name:'Свинина', 
        iconName:images.pig,
    },
    {   id: 3, 
        parentId: 1,
        name:'Баранина', 
        iconName:images.sheep,
    },
    {   id: 4, 
        parentId: 1,
        name:'Телятина', 
        iconName:images.youngCow,
    },
     //Молоко+
    {   id: 5, 
        parentId: 2, 
        name:'Молоко', 
        iconName:images.milk,
    },
    {   id: 6, 
        parentId: 2,
        name:'Сыр', 
        iconName:images.cheese,
    },
    {   id: 7, 
        parentId: 2,
        name:'Творог', 
        iconName:images.cottageCheese,
    },
    {   id: 8, 
        parentId: 2,
        name:'Масло', 
        iconName:images.spread,
    },
    {   id: 9, 
        parentId: 2,
        name:'Сметана', 
        iconName:images.soupCream,
    },
    // Птица+
    {   id: 10, 
        parentId: 3,
        name:'Курица', 
        iconName:images.subChicken,
    },
    {   id: 11, 
        parentId: 3,
        name:'Цыпленок', 
        iconName:images.chick,
    },
    {   id: 12, 
        parentId: 3,
        name:'Гусь', 
        iconName:images.goose,
    },
    {   id: 13, 
        parentId: 3,
        name:'Утка', 
        iconName:images.duck,
    },
    {   id: 14, 
        parentId: 3,
        name:'Индейка', 
        iconName:images.turkey,
    },
    {   id: 15, 
        parentId: 3,
        name:'Яйца', 
        iconName:images.eggs,
    },
    // Овощи
    {   id: 16, 
        parentId: 4,
        name:'Картофель', 
        iconName:images.potato,
    },
    {   id: 17, 
        parentId: 4,
        name:'Помидоры', 
        iconName:images.tomato,
    },
    {   id: 18, 
        parentId: 4,
        name:'Огурцы', 
        iconName:images.cucumber,
    },
    {   id: 19, 
        parentId: 4,
        name:'Капуста', 
        iconName:images.cabbage,
    },
    {   id: 20, 
        parentId: 4,
        name:'Морковь', 
        iconName:images.carrot,
    },
    {   id: 21, 
        parentId: 4,
        name:'Картофель', 
        iconName:images.potato,
    },
    {   id: 22, 
        parentId: 4,
        name:'Лук', 
        iconName:images.onion,
    },
    {   id: 23, 
        parentId: 4,
        name:'Чеснок', 
        iconName:images.garlic,
    },
    {   id: 24, 
        parentId: 4,
        name:'Свекла', 
        iconName:images.beetroot,
    },
    {   id: 25, 
        parentId: 4,
        name:'Зелень', 
        iconName:images.greens,
    },
    // Фрукты
    {   id: 26, 
        parentId: 5,
        name:'Яблоки', 
        iconName:images.apple,
    },
    {   id: 27, 
        parentId: 5,
        name:'Слива', 
        iconName:images.plum,
    },
    {   id: 28, 
        parentId: 5,
        name:'Вишня', 
        iconName:images.cherries,
    },
    {   id: 29, 
        parentId: 5,
        name:'Груша', 
        iconName:images.pear,
    },
    // Ягоды
    {   id: 30, 
        parentId: 6,
        name:'Земляника', 
        iconName:images.strawberry_2,
    },
    {   id: 31, 
        parentId: 6,
        name:'Черника', 
        iconName:images.blueberry,
    },
    {   id: 32, 
        parentId: 6,
        name:'Брусника', 
        iconName:images.cowberry,
    },
    {   id: 33, 
        parentId: 6,
        name:'Клюква', 
        iconName:images.cranberry,
    },
    {   id: 34, 
        parentId: 6,
        name:'Клубника', 
        iconName:images.strawberry_1,
    },
    {   id: 35, 
        parentId: 6,
        name:'Смородина', 
        iconName:images.currant,
    },
    {   id: 36, 
        parentId: 6,
        name:'Малина', 
        iconName:images.raspberries,
    },
    {   id: 37, 
        parentId: 6,
        name:'Крыжовник', 
        iconName:images.gooseberry,
    },
    // Грибы
    {   id: 38, 
        parentId: 7,
        name:'Белые', 
        iconName:images.mushroomWhite,
    },
    {   id: 39, 
        parentId: 7,
        name:'Лисички', 
        iconName:images.chanterelle,
    },
    // Мед+
    {   id: 40, 
        parentId: 8,
        name:'Мед', 
        iconName:images.subHoney,
    },
    {   id: 41, 
        parentId: 8,
        name:'Соты', 
        iconName:images.apitherapy,
    },
    {   id: 42, 
        parentId: 8,
        name:'Перга', 
        iconName:images.honeycomb,
    },
    {   id: 43, 
        parentId: 8,
        name:'Воск', 
        iconName:images.wax,
    },
]